### ISSUE TITLE
aftter call funtion FlutterLogs.logInfo("TAG", "subTag", "My Log Message"); (Flutter 1.25.0.pre.141)

### ISSUE THREAD

**Issue by chanthavong** [umair13adil/flutter_logs#1]
error this on run application
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method logThis on channel flutter_logs)

**Comment by umair13adil** [comment]
@chanthavong Is this happening on an example app or your project?

**Comment by tehsunnliu** [comment]
After updating Flutter to 2.0 I've started getting this error on release mode. In debug, however, it works fine.

**Comment by ibrahim135** [comment]
MissingPluginException(No implementation found for method logThis on channel flutter_logs)
       at MethodChannel._invokeMethod(platform_channel.dart:294)
       at FlutterLogs.logError(flutter_logs.dart:269)
Flutter: V3.3.4 
Happens in debug too sometimes
