### ISSUE TITLE
exportLogs should return Future<void> instead of void

### ISSUE THREAD

**Issue by PhenixZeller** [umair13adil/flutter_logs#28]
Currently when you use `FlutterLogs.exportLogs();` in an async function, you can´t await it, because it is not a Future.

https://github.com/umair13adil/flutter_logs/blob/174350f1039dfeca7e175fe17b2922fb70e0660b/lib/flutter_logs.dart#L301

**Comment by umair13adil** [comment]
@PhenixZeller Noted, this will be done in the next release of the plugin.

**Comment by MrCsabaToth** [comment]
In the pull request I converted all `static void async` to return `Future<void>`
