### ISSUE TITLE
Offer millisecond resolution timestamp

### ISSUE THREAD

**Issue by MrCsabaToth** [umair13adil/flutter_logs#29]
The current timestamps offer only second resolution, I need millisecond resolution. Fortunately 10 month ago PLogs got a new `TIME_FORMAT_READABLE_2` which has milliseconds: https://github.com/umair13adil/RxLogs/blob/master/plog/src/main/java/com/blackbox/plog/pLogs/formatter/TimeStampFormat.kt

**Comment by umair13adil** [comment]
@MrCsabaToth I will enable this in the next release of the plugin.
