### ISSUE TITLE
"This app is using a deprecated version of the Android embedding."

### ISSUE THREAD

**Issue by MrCsabaToth** [umair13adil/flutter_logs#37]
> This app is using a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
> Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by MrCsabaToth** [comment]
Ok, the compiler link was not targeted enough, here is a better one: https://docs.flutter.dev/development/platform-integration/android/plugin-api-migration
TO em it seems that you implement both V2 API (onAttachedToActivity, onDetachedFromActivityForConfigChanges, onReattachedToActivityForConfigChanges, onDetachedFromActivity) and older API (onAttachedToEngine, onDetachedFromEngine)? Maybe it's just about minimum Flutter SDK version in pubspec? V1 is looong time deprecated, should let go.

**Comment by umair13adil** [comment]
This is fixed in v2.1.7

**Comment by MrCsabaToth** [comment]
Awesome
