### ISSUE TITLE
flutter_logs does not support flutter_web?

### ISSUE THREAD

**Issue by BlackToothGrin96** [umair13adil/flutter_logs#5]
Hi, I have an app that uses flutter_logs and have recently upgraded to flutter 2.

I wanted to try out flutter web but when I build and run the app, I get the error:

`MissingPluginException(No implementation found for method initLogs on channel flutter_logs)`

The app works fine on Android as I have a few live systems using it now.

Do you know of any reason why this shouldn't work with flutter web?

Version info:

`Flutter (Channel beta, 2.0.1, on Linux, locale en_GB.UTF-8)`
`Android toolchain - develop for Android devices (Android SDK version 28.0.3)`

Great work on the package btw - so far the best logging tool I've used with flutter.

Please let me know if you need any more info.

**Comment by umair13adil** [comment]
It's not currently supported on web. I will work on an update, after that it's support will be available soon.

**Comment by MongkolJ** [comment]
I've the same error when I build but this error occurred even for android

**Comment by umair13adil** [comment]
No support for the web is planned.
