### ISSUE TITLE
setMethodCallHandler callback not getting hit

### ISSUE THREAD

**Issue by vysakhvasanth** [umair13adil/flutter_logs#50]
I'm using the latest version **2.1.10**.

When I export the logs, I'm trying to capture the callback to upload file to a server. But the callback registered is not getting hit.

```
FlutterLogs.channel.setMethodCallHandler((call) async {
      if (call.method == 'logsExported') {
        var zipName = call.arguments.toString();
      } else if (call.method == 'logsPrinted') {
        print(call.arguments.toString());
      }
}
```

**Comment by vysakhvasanth** [comment]
I've registered the callback in the `main.dart` entry point right after the setup call `FlutterLogs.initLogs`

**Comment by ced1check** [comment]
Same problem here, not sure what I'm doing wrong, I run this:

```
await FlutterLogs.init(...);
```

Then copy-pasted the channel setup from readme added a log at the very start but it never shows!?

```
FlutterLogs.channel.setMethodCallHandler((call) async {
  logInfo(message: 'Received FlutterLogs callback: ${call.method}');
}

```

**Comment by ced1check** [comment]
Ended-up using flutter_archive to export logs into a ZIP file:

```
      Directory dir = Directory("${externalDirectory.path}/Logs");

      final zipFile = File("${externalDirectory.path}/Logs_${DateFormat('yyyy-MM-dd_HH-mm').format(DateTime.now())}.zip");
      await ZipFile.createFromDirectory(sourceDir: dir, zipFile: zipFile, recurseSubDirs: true);

      logInfo(message: "Logs zipped into ${zipFile.path}");

```

**Comment by neiljaywarner** [comment]
@ced1check  what did you end up with?

**Comment by umair13adil** [comment]
![Uploading Screenshot 2024-09-07 at 1.40.25 PM.png…]()
