### ISSUE TITLE
dependency old?

### ISSUE THREAD

**Issue by leejonggun** [umair13adil/flutter_logs#55]
When I build my flutter app, I got this error.

* What went wrong:
Execution failed for task ':flutter_logs:generateReleaseRFile'.
> Could not resolve all files for configuration ':flutter_logs:releaseCompileClasspath'.
   > Could not find com.github.umair13adil:RxLogs:1.0.18.
     Required by:
         project :flutter_logs

I can confirm the com.github.umair13adil:RxLogs has `v1.0.18`, as you know. ref) https://github.com/umair13adil/RxLogs/tree/v1.0.18

Could you take a look of this build.gradle? https://github.com/umair13adil/flutter_logs/blob/master/android/build.gradle#L50
Wonder if `1.0.18` fine or not, is it `v1.0.18`?

**Comment by willyfromtheblock** [comment]
Started to get this issue as well in my github actions pipeline for api level 31

**Comment by EduardoAlberti** [comment]
same issue here, any work around?

**Comment by neiljaywarner** [comment]
same here gitlab ci/cd pipeline, also even weirder (to me) it seems intermittent

**Comment by leejonggun** [comment]
flutter_logs in my app still try to resolve 1.0.18... Need a version update to 2.1.11?
I think your fix(https://github.com/neiljaywarner/flutter_logs/commit/c7c69f10829558e9baa2f723597cc9b304746b2b) is fine, but it doesn't fix my app... Hmm

**Comment by neiljaywarner** [comment]
Does pubspeck.lock say the new version number?
I had a bit of that at first which is why I bumped the version but yeah a
full release would be great

....sent from my phone

**Comment by leejonggun** [comment]
PR57(https://github.com/umair13adil/flutter_logs/pull/57) is merged. my app build success! :) Thank you.
