### ISSUE TITLE
Namespace error on Gradle 8.0

### ISSUE THREAD

**Issue by john011022** [umair13adil/flutter_logs#59]
When you try to build the app using Gradle 8.0 it gives an error saying namespace is not defined for flutter_logs.

If I downgrade the gradle version the app is built and deployed.

Configuration That does not work

classpath 'com.android.tools.build:gradle:8.1.4'
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-all.zip

**Comment by Hyla96** [comment]
https://github.com/umair13adil/flutter_logs/pull/61

**Comment by umair13adil** [comment]
The issue has been resolved in version 2.1.12
