### ISSUE TITLE
Please upgrade work manager to at least 2.8.1

### ISSUE THREAD

**Issue by neiljaywarner** [umair13adil/flutter_logs#62]
a) Workmanager version is old
1) Current version is 2.9
2) 2.8.0 was released almost a year ago (feb 2023) and seems to have several meaningful updated

see https://developer.android.com/jetpack/androidx/releases/work

b) it clashes with https://pub.dev/packages/flutter_background_geolocation/changelog in a way that produces the below without a super obvious workaround that i can think of right now :) 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by umair13adil** [comment]
The issue has been resolved in version 2.1.12
