### ISSUE TITLE
CI/CD pipeline - flutter  app

### ISSUE THREAD

**Issue by hamzaoubouzid** [umair13adil/flutter_logs#77]
Hi , I am currently working on setting up a CI/CD pipeline using Jenkins and have encountered an issue during the release of the APK. Specifically, I am receiving the following error:
![Capture](https://github.com/user-attachments/assets/0e329ed4-1cd3-4bc9-b4de-b9445676cc33)

* What went wrong:
Execution failed for task ':flutter_logs:generateReleaseRFile'.
> Could not resolve all files for configuration ':flutter_logs:releaseCompileClasspath'.
   > Failed to transform RxLogs-1.0.20.aar (com.github.umair13adil:RxLogs:1.0.20) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find RxLogs-1.0.20.aar (com.github.umair13adil:RxLogs:1.0.20).
        Searched in the following locations:
            https://jitpack.io/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.aar

**Comment by kwaku-pistis** [comment]
Also facing the same issue with codemagic

**Comment by aberutti-convorelay** [comment]
Also facing this issue. In the past this PR(#57 ) solved it

**Comment by kwaku-pistis** [comment]
any idea how I can use this PR(#57) in my code? and what version of flutter_logs should I downgrade to?

**Comment by aberutti-convorelay** [comment]
> any idea how I can use this PR(#57) in my code? and what version of flutter_logs should I downgrade to?

@kwaku-pistis well, if you need to solve this asap you should fork this repo and change the dependency "com.github.umair13adil:RxLogs:1.0.20" for "com.github.umair13adil:RxLogs:1.0.23" in the build gradle

**Comment by kwaku-pistis** [comment]
> > any idea how I can use this PR(#57) in my code? and what version of flutter_logs should I downgrade to?
> 
> @kwaku-pistis well, if you need to solve this asap you should fork this repo and change the dependency "com.github.umair13adil:RxLogs:1.0.20" for "com.github.umair13adil:RxLogs:1.0.23" in the build gradle

@aberutti-convorelay  thank you

**Comment by karlleach** [comment]
the url is wrong should be 
https://[jitpack.io/com/github/umair13adil/RxLogs/v1.0.20/RxLogs-1.0.20.aar](https://jitpack.io/com/github/umair13adil/RxLogs/v1.0.20/RxLogs-1.0.20.aar)

**Comment by hamzaoubouzid** [comment]
Hi  @kwaku-pistis and @aberutti-convorelay 
I have resolved the issue. It was related to the packages you installed in the project

**Comment by aberutti-convorelay** [comment]
@hamzaoubouzid Hi. Can you elaborate please? How do you resolve it?

**Comment by TecLinkAutomacao** [comment]
Hi, I have the same issue here ! Can you elaborate please? How do you resolve it?
I'm using flutter_logs: 2.1.12
when I try to build shows this:

![logs](https://github.com/user-attachments/assets/21eec763-02d0-4716-bae0-eb5e99b79691)

I'm using this flutter version:

![image](https://github.com/user-attachments/assets/873f3554-4a4e-42e0-b9ad-1d689fa6fee7)

Tks!

**Comment by hamzaoubouzid** [comment]
> @hamzaoubouzid Hi. Can you elaborate please? How do you resolve it?
   can you send me your pubspec.yaml

**Comment by hamzaoubouzid** [comment]
hi  @aberutti-convorelay  can you send me your pubspec.yaml

**Comment by umair13adil** [comment]
Please use version 1.0.22. There is an issue at jCenter that's why the version had to be updated.
