### ISSUE TITLE
'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

### ISSUE THREAD

**Issue by yoer** [umair13adil/flutter_logs#79]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_logs:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 28s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by yoer** [comment]
![image](https://github.com/user-attachments/assets/1873da15-670d-45cb-be53-a264462f83bc)

Why are there two sourceCompatibility here, 1_8 and 17 ?

``` 
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
```

I deleted the following VERSION_17 and everything went fine.

Please fix this as soon as possible!

**Comment by yoer** [comment]
@umair13adil

**Comment by umair13adil** [comment]
@yoer The new version is published with this fixed.

flutter_logs: ^2.2.1

**Comment by yoer** [comment]
wow! thans a lot!!
