### ISSUE TITLE
support null safety

### ISSUE THREAD

**Issue by MichalNemec** [umair13adil/flutter_logs#8]
flutter build apk --debug

 Building with sound null safety 

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_logs

For solutions, see https://dart.dev/go/unsound-null-safety
                                                                        
                                                                        
FAILURE: Build failed with an exception

**Comment by MrCsabaToth** [comment]
Does https://github.com/umair13adil/flutter_logs/commit/9fb39dcea86caf445b2260623761acccaf54d866 fix this?

**Comment by umair13adil** [comment]
Yes, it should be closed.
